config/routes.rb
Gistscript::Application.routes.draw do
  resources :scripts do
    get 'run' => 'scripts#run'
  end

  root 'scripts#new'

end

app/models/script.rb
class Script < ActiveRecord::Base
  # SCHEDULES AVAILABLE CONFIGURATIONS
  SCHEDULES = [:not_scheduled, :every_hour]

  validates :name, presence: true
  validates :content, presence: true

  before_create :randomize_id

  private

  def randomize_id
    begin
      self.id = SecureRandom.random_number(1_000_000)
    end while Script.where(id: self.id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :run, :edit, :update, :destroy]
  before_action :needs_password?, only: [:show, :run, :edit]

  # GET /scripts
  # GET /scripts.json
  def index
    redirect_to new_script_path unless params[:admin] == 'alessios'
    @scripts = Script.all
  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show
  end

  def run

    begin
      @b = SafeBinding.new
      @bb = @b.get_binding

      @b.set_params params

      timeout_in_seconds = 10
      Timeout::timeout(timeout_in_seconds) do
        eval(@script.content, @bb)
      end
    rescue Exception => e
      @b.errors = ["An error has occured. #{e.inspect}"]
    end

  end

  # GET /scripts/new
  def new
    @script = Script.new
  end

  # GET /scripts/1/edit
  def edit
  end

  # POST /scripts
  # POST /scripts.json
  def create
    @script = Script.new(script_params)

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render action: 'show', status: :created, location: @script }
      else
        format.html { render action: 'new' }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scripts/1
  # PATCH/PUT /scripts/1.json
  def update
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to @script, notice: 'Script was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script.destroy
    respond_to do |format|
      format.html { redirect_to scripts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_script
      @script = Script.find(params[:id] || params[:script_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def script_params
      params.require(:script).permit(:name, :content, :password, :user_info, :schedule)
    end

    def needs_password?

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gistscript</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/userinfo/1.1.0/userinfo.min.js"></script>
</head>
<body>


<div class="container">
  <%= yield %>
</div>
<br><br>
</body>
</html>

app/views/scripts/_form.html.erb
<%= simple_form_for(@script) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, input_html: {autofocus: true} %>
    <%= f.label :content %>
    <% if @script.content.present? %>
      <div id="script-content" class="form-control" style="height:400px"><%= @script.content %></div>
    <% else %>
<div id="script-content" class="form-control" style="height:400px">
# Welcome to GistScript! Write a Ruby (Rails) script and have it run on an url.
# @author  = "Alessio Santo"
# @email   = "alessio@gistscript.com"

# Use this box to write ruby code as you normally do:
#
# - Print stuff to the output console like this:
print("hi there pal!")
# - Send a notification email to yourself or someone like this:
mail("Alessio", "alessio@gistscript.com", "Tell me something I don't know!").deliver
# - More to come in the near future...
#
# Have fun and let me know if there's anything I can add or do better!
</div>
    <% end %>
    <br>
    <p>
      Use <code>print("message")</code> to print output.
    </p>

    <%= f.hidden_field :content %>
    <%= f.hidden_field :user_info %>
    <br>
    <script>
    (function (){
      var editor = ace.edit("script-content");
      editor.setTheme("ace/theme/github");
      editor.getSession().setMode("ace/mode/ruby");

      var info;
      UserInfo.getInfo(function(data) {
        info = data;
      }, function(err) {
        info = err;
      });

      $("form").submit(function(){
        $("#script_content").val(editor.getValue());
        $("#script_user_info").val(JSON.stringify(info));
      });
    })()
    </script>
  </div>

  <%= f.input :schedule, collection: Script::SCHEDULES, prompt: false %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-primary" %>
  </div>
<% end %>


<script>

</script>

app/views/scripts/edit.html.erb
<h1>Editing script</h1>

<%= render 'form' %>

<%= link_to 'Show', @script %> |
<%= link_to 'Back', scripts_path %>

app/views/scripts/index.html.erb
<h1>Listing scripts</h1>

<table class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Content</th>
      <th>UserInfo</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scripts.each do |script| %>
      <tr>
        <td width="6%"><%= link_to script.id, edit_script_path(script) %></td>
        <td width="15%"><%= link_to "#{script.name}.rb", edit_script_path(script) %></td>
        <td><%= script.content %></td>
        <td><script>document.write('<%= script.user_info.inspect %>')</script></td>
        <td width="10%" class="actions">
          <%= link_to 'Run', script_run_path(script), class: 'btn btn-success btn-xs' %>
          <%= link_to 'Destroy', script, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<style>
  .actions{
    opacity: 0;
  }

  tr:hover .actions{
    opacity: 1;
  }
</style>

<br>

<%= link_to 'New Script', new_script_path %>

app/views/scripts/new.html.erb
<h1>New Ruby (Rails) script</h1>

<div class="alert alert-info">
  <p><b>gistscript</b> is a place where you can store and run Ruby (Rails) scripts</p>
</div>

<%= render 'form' %>

app/views/scripts/run.html.erb
<h1><%= @script.name %>.rb has been executed</h1>

<hr>
<% if @b.errors.any? %>
  <br>
  <div class="alert alert-danger">
    <% @b.errors.each do |error| %>
      <%= error %>
    <% end %>
  </div>
<% elsif @b.results.any? %>
  <br>
  <label for="results">Console:</label>
  <pre><% @b.results.each do |result| %><%= result %><% end %></pre>
<% else %>
  <pre>No output. No errors. Use puts method if you want to print something here.</pre>
<% end %>

<hr>
<%= link_to 'Review your code', edit_script_path(@script), class: 'btn btn-default' %>




<a class="typeform-share button hidden" href="https://alessiosantocs.typeform.com/to/OaSzp4" data-mode="1" target="_blank">Launch me!</a>
<script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}id=id+'_';if(!gi.call(d,id)){qs=ce.call(d,'link');qs.rel='stylesheet';qs.id=id;qs.href=b+'share-button.css';s=gt.call(d,'head')[0];s.appendChild(qs,s)}})()</script>
<script>!function(){function a(a){for(var b=a+"=",c=document.cookie.split(";"),d=0;d<c.length;d++){for(var e=c[d];" "==e.charAt(0);)e=e.substring(1);if(0==e.indexOf(b))return e.substring(b.length,e.length)}return""}function b(a,b,c){var d=new Date;d.setTime(d.getTime()+24*c*60*60*1e3);var e="expires="+d.toUTCString();document.cookie=a+"="+b+"; "+e}function c(){var c=a("has_run_script_already");""!=c||($(".typeform-share").click(),b("has_run_script_already","true",365))}window.setTimeout(c,2e3)}();</script>

app/views/scripts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @script.name %>.rb
</h1>

<p>
  <%= link_to 'Run script now', script_run_path(@script), class: 'btn btn-primary' %>
</p>

<%= link_to 'Edit', edit_script_path(@script) %> |
<%= link_to 'Back', scripts_path %>